AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - test/**
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# Customize rules
Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 40
Metrics/BlockLength:
  Max: 60
Style/ModuleFunction:
  EnforcedStyle: extend_self
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': ()
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true
Style/AndOr:
  Description: 'Use &&/|| instead of and/or.'
  StyleGuide: '#no-and-or-or'
  Enabled: true