AllCops:
  Includes:
    - Rakefile
    - config.ru
  Excludes:
    - test/**
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# Customize rules
Metrics/LineLength:
  Max: 160