sudo: required
dist: trusty
notifications:
  email: false
language: ruby
rvm:
  - 2.4.1
env:
  - RAILS_ENV=test
cache:
  bundler: true
services:
  - postgresql
  apt:
    packages:
    - postgresql-9.6
    - postgresql-contrib-9.6
  postgresql: "9.6"
before_script:
  - sudo service postgresql start
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rspec
  - CODECLIMATE_REPO_TOKEN=b7b7d9e4c5aa6b0913fd634637e4fa0e0009b4830903f950e851468343a7cb9f
  - bundle exec codeclimate-test-reporter
