version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem uninstall bcrypt-ruby
  - gem uninstall bcrypt
  - gem install bcrypt --platform=ruby
  - bundle install
build: off

test_script:
  - rspec
