version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install
  - git clone https://github.com/codahale/bcrypt-ruby.git
  - cd bcrypt-ruby
  - gem build bcrypt.gemspec
  - gem install gem-compiler
  - gem compile bcrypt-3.1.11.gem
  - gem install ./bcrypt-3.1.11-x86-mingw32.gem
  - cd ..
build: off
platform: Any CPU
init:
- ps: >-
    Set-Content "c:\program files\postgresql\9.6\data\pg_hba.conf" "host    all             all             ::1/128            trust"
    Add-Content "c:\program files\postgresql\9.6\data\pg_hba.conf" "host    all             all             127.0.0.1/32            trust"
    $env:Path += ";c:\program files\postgresql\9.6\bin"
services: postgresql
build_script:
- ps: >-
    psql -U postgres -c "CREATE ROLE mifrill LOGIN SUPERUSER CREATEDB CREATEROLE;"
test_script:
  - bin/rails db:setup
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rspec
