version: "{build}"

install:
  - set PATH=C:\Ruby24\bin;%PATH%
  - gem update --system --no-document
  - gem install bundler --no-document
  - bundle install
build: off

test_script:
  - bundle exec rspec
