version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install
  - gem install bcrypt --platform=ruby
  - gem install bcrypt-ruby
build: off

test_script:
  - rspec
