version: "{build}"

environment:
  matrix:
    - RUBY_VERSION: 24
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install
  - git clone https://github.com/codahale/bcrypt-ruby.git
  - cd bcrypt-ruby
  - gem build bcrypt.gemspec
  - gem install gem-compiler
  - gem compile bcrypt-3.1.11.gem
  - gem install bcrypt-3.1.11-x64-mingw32.gem --local
build: off

test_script:
  - bundle exec rspec
