# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cda20ede82f4dfa360285ba7547be8e0eca0e179ec51b3d037f92022b44814024f28a7e45086656bf6dc213aae83df1bdd4df716265904e4799b1cab024bc7ae

test:
  secret_key_base: 85d682bc4c1232af8d5108cac48faa3fb467a3c640fdbb6475c2fbbd287450d8f204881628cccdc1af53b5936c4520abd85c2db739c863f0c86ad3011c071210

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
